title: 조강현
description: 게임 프로그래머
site_title: '조강현의 포토폴리오'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: JoKangHyeon
blog_url: 
email: jokh980324@naver.com

# absolute or relative

# Google Analytics ID
google_analytics: 
